// This file was automatically generated by `digital/python/cmbtr.py`
//
// Loading of LFSR pins:
//   25  : 3
//   31  : 3
//   28  : 4
//   6   : 4
//   16  : 4
//   21  : 4
//   17  : 5
//   35  : 5
//   2   : 5
//   30  : 5
//   36  : 5
//   10  : 5
//   3   : 5
//   24  : 6
//   7   : 6
//   19  : 6
//   13  : 6
//   12  : 6
//   37  : 6
//   27  : 6
//   23  : 6
//   34  : 6
//   8   : 6
//   20  : 6
//   29  : 6
//   5   : 6
//   14  : 6
//   42  : 6
//   15  : 6
//   22  : 6
//   4   : 6
//   9   : 6
//   39  : 6
//   18  : 6
//   11  : 6
//   40  : 6
//   33  : 6
//   1   : 7
//   41  : 7
//   38  : 7
//   26  : 7
//   0   : 7
//   32  : 7
// Loading of CASR pins:
//   13  : 6
//   19  : 6
//   7   : 6
//   1   : 6
//   23  : 6
//   2   : 6
//   8   : 6
//   5   : 6
//   27  : 6
//   6   : 6
//   28  : 6
//   32  : 6
//   15  : 6
//   25  : 6
//   9   : 6
//   33  : 6
//   34  : 7
//   30  : 7
//   3   : 7
//   4   : 7
//   17  : 7
//   31  : 7
//   20  : 7
//   11  : 7
//   36  : 7
//   29  : 7
//   24  : 7
//   35  : 7
//   0   : 7
//   18  : 7
//   26  : 7
//   14  : 7
//   10  : 7
//   22  : 7
//   12  : 7
//   21  : 7
//   16  : 7

// Automatically generated by a python script (`cmbtr.py`)

`default_nettype none

`ifndef RTL

module cmbtr (
  input  wire [79:0]             i_cmbtr_state,     // [79:37] LFSR state, [36:0] CASR state
  output wire [243-1:0]     o_cmbtr_randbits); // random bits output vector

  wire [42:0] lfsr_state = i_cmbtr_state[79:37];
  wire [36:0] casr_state = i_cmbtr_state[36:0];


assign o_cmbtr_randbits[0] = lfsr_state[1] ^ casr_state[34];
assign o_cmbtr_randbits[1] = lfsr_state[24] ^ casr_state[30];
assign o_cmbtr_randbits[2] = lfsr_state[41] ^ casr_state[13];
assign o_cmbtr_randbits[3] = lfsr_state[7] ^ casr_state[3];
assign o_cmbtr_randbits[4] = lfsr_state[19] ^ casr_state[19];
assign o_cmbtr_randbits[5] = lfsr_state[17] ^ casr_state[7];
assign o_cmbtr_randbits[6] = lfsr_state[13] ^ casr_state[4];
assign o_cmbtr_randbits[7] = lfsr_state[38] ^ casr_state[1];
assign o_cmbtr_randbits[8] = lfsr_state[1] ^ casr_state[17];
assign o_cmbtr_randbits[9] = lfsr_state[41] ^ casr_state[23];
assign o_cmbtr_randbits[10] = lfsr_state[12] ^ casr_state[31];
assign o_cmbtr_randbits[11] = lfsr_state[37] ^ casr_state[20];
assign o_cmbtr_randbits[12] = lfsr_state[26] ^ casr_state[11];
assign o_cmbtr_randbits[13] = lfsr_state[25] ^ casr_state[1];
assign o_cmbtr_randbits[14] = lfsr_state[41] ^ casr_state[36];
assign o_cmbtr_randbits[15] = lfsr_state[27] ^ casr_state[2];
assign o_cmbtr_randbits[16] = lfsr_state[23] ^ casr_state[7];
assign o_cmbtr_randbits[17] = lfsr_state[34] ^ casr_state[29];
assign o_cmbtr_randbits[18] = lfsr_state[8] ^ casr_state[24];
assign o_cmbtr_randbits[19] = lfsr_state[31] ^ casr_state[31];
assign o_cmbtr_randbits[20] = lfsr_state[20] ^ casr_state[35];
assign o_cmbtr_randbits[21] = lfsr_state[29] ^ casr_state[8];
assign o_cmbtr_randbits[22] = lfsr_state[35] ^ casr_state[0];
assign o_cmbtr_randbits[23] = lfsr_state[5] ^ casr_state[5];
assign o_cmbtr_randbits[24] = lfsr_state[24] ^ casr_state[27];
assign o_cmbtr_randbits[25] = lfsr_state[14] ^ casr_state[18];
assign o_cmbtr_randbits[26] = lfsr_state[7] ^ casr_state[6];
assign o_cmbtr_randbits[27] = lfsr_state[20] ^ casr_state[30];
assign o_cmbtr_randbits[28] = lfsr_state[23] ^ casr_state[35];
assign o_cmbtr_randbits[29] = lfsr_state[42] ^ casr_state[26];
assign o_cmbtr_randbits[30] = lfsr_state[15] ^ casr_state[4];
assign o_cmbtr_randbits[31] = lfsr_state[22] ^ casr_state[28];
assign o_cmbtr_randbits[32] = lfsr_state[2] ^ casr_state[27];
assign o_cmbtr_randbits[33] = lfsr_state[28] ^ casr_state[31];
assign o_cmbtr_randbits[34] = lfsr_state[4] ^ casr_state[5];
assign o_cmbtr_randbits[35] = lfsr_state[9] ^ casr_state[3];
assign o_cmbtr_randbits[36] = lfsr_state[6] ^ casr_state[0];
assign o_cmbtr_randbits[37] = lfsr_state[20] ^ casr_state[32];
assign o_cmbtr_randbits[38] = lfsr_state[14] ^ casr_state[15];
assign o_cmbtr_randbits[39] = lfsr_state[0] ^ casr_state[30];
assign o_cmbtr_randbits[40] = lfsr_state[32] ^ casr_state[35];
assign o_cmbtr_randbits[41] = lfsr_state[41] ^ casr_state[24];
assign o_cmbtr_randbits[42] = lfsr_state[5] ^ casr_state[34];
assign o_cmbtr_randbits[43] = lfsr_state[20] ^ casr_state[14];
assign o_cmbtr_randbits[44] = lfsr_state[13] ^ casr_state[10];
assign o_cmbtr_randbits[45] = lfsr_state[17] ^ casr_state[18];
assign o_cmbtr_randbits[46] = lfsr_state[32] ^ casr_state[22];
assign o_cmbtr_randbits[47] = lfsr_state[39] ^ casr_state[14];
assign o_cmbtr_randbits[48] = lfsr_state[18] ^ casr_state[25];
assign o_cmbtr_randbits[49] = lfsr_state[1] ^ casr_state[12];
assign o_cmbtr_randbits[50] = lfsr_state[9] ^ casr_state[9];
assign o_cmbtr_randbits[51] = lfsr_state[4] ^ casr_state[26];
assign o_cmbtr_randbits[52] = lfsr_state[29] ^ casr_state[1];
assign o_cmbtr_randbits[53] = lfsr_state[30] ^ casr_state[30];
assign o_cmbtr_randbits[54] = lfsr_state[4] ^ casr_state[21];
assign o_cmbtr_randbits[55] = lfsr_state[36] ^ casr_state[2];
assign o_cmbtr_randbits[56] = lfsr_state[11] ^ casr_state[15];
assign o_cmbtr_randbits[57] = lfsr_state[16] ^ casr_state[13];
assign o_cmbtr_randbits[58] = lfsr_state[14] ^ casr_state[8];
assign o_cmbtr_randbits[59] = lfsr_state[6] ^ casr_state[16];
assign o_cmbtr_randbits[60] = lfsr_state[40] ^ casr_state[26];
assign o_cmbtr_randbits[61] = lfsr_state[36] ^ casr_state[29];
assign o_cmbtr_randbits[62] = lfsr_state[1] ^ casr_state[21];
assign o_cmbtr_randbits[63] = lfsr_state[17] ^ casr_state[8];
assign o_cmbtr_randbits[64] = lfsr_state[7] ^ casr_state[21];
assign o_cmbtr_randbits[65] = lfsr_state[41] ^ casr_state[27];
assign o_cmbtr_randbits[66] = lfsr_state[8] ^ casr_state[35];
assign o_cmbtr_randbits[67] = lfsr_state[12] ^ casr_state[27];
assign o_cmbtr_randbits[68] = lfsr_state[9] ^ casr_state[34];
assign o_cmbtr_randbits[69] = lfsr_state[11] ^ casr_state[35];
assign o_cmbtr_randbits[70] = lfsr_state[8] ^ casr_state[9];
assign o_cmbtr_randbits[71] = lfsr_state[4] ^ casr_state[12];
assign o_cmbtr_randbits[72] = lfsr_state[27] ^ casr_state[11];
assign o_cmbtr_randbits[73] = lfsr_state[32] ^ casr_state[9];
assign o_cmbtr_randbits[74] = lfsr_state[4] ^ casr_state[31];
assign o_cmbtr_randbits[75] = lfsr_state[35] ^ casr_state[4];
assign o_cmbtr_randbits[76] = lfsr_state[14] ^ casr_state[22];
assign o_cmbtr_randbits[77] = lfsr_state[30] ^ casr_state[27];
assign o_cmbtr_randbits[78] = lfsr_state[0] ^ casr_state[21];
assign o_cmbtr_randbits[79] = lfsr_state[7] ^ casr_state[15];
assign o_cmbtr_randbits[80] = lfsr_state[15] ^ casr_state[23];
assign o_cmbtr_randbits[81] = lfsr_state[42] ^ casr_state[11];
assign o_cmbtr_randbits[82] = lfsr_state[26] ^ casr_state[29];
assign o_cmbtr_randbits[83] = lfsr_state[13] ^ casr_state[16];
assign o_cmbtr_randbits[84] = lfsr_state[20] ^ casr_state[0];
assign o_cmbtr_randbits[85] = lfsr_state[26] ^ casr_state[8];
assign o_cmbtr_randbits[86] = lfsr_state[22] ^ casr_state[7];
assign o_cmbtr_randbits[87] = lfsr_state[21] ^ casr_state[5];
assign o_cmbtr_randbits[88] = lfsr_state[37] ^ casr_state[34];
assign o_cmbtr_randbits[89] = lfsr_state[28] ^ casr_state[6];
assign o_cmbtr_randbits[90] = lfsr_state[9] ^ casr_state[7];
assign o_cmbtr_randbits[91] = lfsr_state[8] ^ casr_state[25];
assign o_cmbtr_randbits[92] = lfsr_state[10] ^ casr_state[4];
assign o_cmbtr_randbits[93] = lfsr_state[15] ^ casr_state[25];
assign o_cmbtr_randbits[94] = lfsr_state[6] ^ casr_state[11];
assign o_cmbtr_randbits[95] = lfsr_state[40] ^ casr_state[1];
assign o_cmbtr_randbits[96] = lfsr_state[3] ^ casr_state[33];
assign o_cmbtr_randbits[97] = lfsr_state[10] ^ casr_state[19];
assign o_cmbtr_randbits[98] = lfsr_state[25] ^ casr_state[25];
assign o_cmbtr_randbits[99] = lfsr_state[15] ^ casr_state[10];
assign o_cmbtr_randbits[100] = lfsr_state[40] ^ casr_state[20];
assign o_cmbtr_randbits[101] = lfsr_state[38] ^ casr_state[3];
assign o_cmbtr_randbits[102] = lfsr_state[39] ^ casr_state[10];
assign o_cmbtr_randbits[103] = lfsr_state[0] ^ casr_state[8];
assign o_cmbtr_randbits[104] = lfsr_state[12] ^ casr_state[35];
assign o_cmbtr_randbits[105] = lfsr_state[8] ^ casr_state[3];
assign o_cmbtr_randbits[106] = lfsr_state[32] ^ casr_state[0];
assign o_cmbtr_randbits[107] = lfsr_state[10] ^ casr_state[10];
assign o_cmbtr_randbits[108] = lfsr_state[8] ^ casr_state[22];
assign o_cmbtr_randbits[109] = lfsr_state[6] ^ casr_state[1];
assign o_cmbtr_randbits[110] = lfsr_state[14] ^ casr_state[12];
assign o_cmbtr_randbits[111] = lfsr_state[5] ^ casr_state[20];
assign o_cmbtr_randbits[112] = lfsr_state[19] ^ casr_state[12];
assign o_cmbtr_randbits[113] = lfsr_state[28] ^ casr_state[33];
assign o_cmbtr_randbits[114] = lfsr_state[35] ^ casr_state[19];
assign o_cmbtr_randbits[115] = lfsr_state[7] ^ casr_state[17];
assign o_cmbtr_randbits[116] = lfsr_state[32] ^ casr_state[36];
assign o_cmbtr_randbits[117] = lfsr_state[13] ^ casr_state[9];
assign o_cmbtr_randbits[118] = lfsr_state[37] ^ casr_state[28];
assign o_cmbtr_randbits[119] = lfsr_state[30] ^ casr_state[36];
assign o_cmbtr_randbits[120] = lfsr_state[26] ^ casr_state[19];
assign o_cmbtr_randbits[121] = lfsr_state[33] ^ casr_state[33];
assign o_cmbtr_randbits[122] = lfsr_state[18] ^ casr_state[11];
assign o_cmbtr_randbits[123] = lfsr_state[39] ^ casr_state[9];
assign o_cmbtr_randbits[124] = lfsr_state[29] ^ casr_state[36];
assign o_cmbtr_randbits[125] = lfsr_state[1] ^ casr_state[3];
assign o_cmbtr_randbits[126] = lfsr_state[33] ^ casr_state[22];
assign o_cmbtr_randbits[127] = lfsr_state[41] ^ casr_state[33];
assign o_cmbtr_randbits[128] = lfsr_state[18] ^ casr_state[22];
assign o_cmbtr_randbits[129] = lfsr_state[12] ^ casr_state[32];
assign o_cmbtr_randbits[130] = lfsr_state[23] ^ casr_state[8];
assign o_cmbtr_randbits[131] = lfsr_state[25] ^ casr_state[32];
assign o_cmbtr_randbits[132] = lfsr_state[35] ^ casr_state[29];
assign o_cmbtr_randbits[133] = lfsr_state[10] ^ casr_state[26];
assign o_cmbtr_randbits[134] = lfsr_state[20] ^ casr_state[17];
assign o_cmbtr_randbits[135] = lfsr_state[5] ^ casr_state[36];
assign o_cmbtr_randbits[136] = lfsr_state[21] ^ casr_state[20];
assign o_cmbtr_randbits[137] = lfsr_state[12] ^ casr_state[20];
assign o_cmbtr_randbits[138] = lfsr_state[42] ^ casr_state[17];
assign o_cmbtr_randbits[139] = lfsr_state[32] ^ casr_state[20];
assign o_cmbtr_randbits[140] = lfsr_state[22] ^ casr_state[27];
assign o_cmbtr_randbits[141] = lfsr_state[3] ^ casr_state[10];
assign o_cmbtr_randbits[142] = lfsr_state[2] ^ casr_state[30];
assign o_cmbtr_randbits[143] = lfsr_state[1] ^ casr_state[14];
assign o_cmbtr_randbits[144] = lfsr_state[23] ^ casr_state[2];
assign o_cmbtr_randbits[145] = lfsr_state[32] ^ casr_state[7];
assign o_cmbtr_randbits[146] = lfsr_state[28] ^ casr_state[2];
assign o_cmbtr_randbits[147] = lfsr_state[2] ^ casr_state[13];
assign o_cmbtr_randbits[148] = lfsr_state[33] ^ casr_state[6];
assign o_cmbtr_randbits[149] = lfsr_state[4] ^ casr_state[24];
assign o_cmbtr_randbits[150] = lfsr_state[19] ^ casr_state[32];
assign o_cmbtr_randbits[151] = lfsr_state[30] ^ casr_state[24];
assign o_cmbtr_randbits[152] = lfsr_state[19] ^ casr_state[21];
assign o_cmbtr_randbits[153] = lfsr_state[31] ^ casr_state[29];
assign o_cmbtr_randbits[154] = lfsr_state[21] ^ casr_state[26];
assign o_cmbtr_randbits[155] = lfsr_state[13] ^ casr_state[2];
assign o_cmbtr_randbits[156] = lfsr_state[40] ^ casr_state[24];
assign o_cmbtr_randbits[157] = lfsr_state[26] ^ casr_state[26];
assign o_cmbtr_randbits[158] = lfsr_state[0] ^ casr_state[25];
assign o_cmbtr_randbits[159] = lfsr_state[22] ^ casr_state[17];
assign o_cmbtr_randbits[160] = lfsr_state[26] ^ casr_state[9];
assign o_cmbtr_randbits[161] = lfsr_state[18] ^ casr_state[17];
assign o_cmbtr_randbits[162] = lfsr_state[22] ^ casr_state[4];
assign o_cmbtr_randbits[163] = lfsr_state[27] ^ casr_state[4];
assign o_cmbtr_randbits[164] = lfsr_state[18] ^ casr_state[28];
assign o_cmbtr_randbits[165] = lfsr_state[33] ^ casr_state[28];
assign o_cmbtr_randbits[166] = lfsr_state[23] ^ casr_state[1];
assign o_cmbtr_randbits[167] = lfsr_state[37] ^ casr_state[33];
assign o_cmbtr_randbits[168] = lfsr_state[39] ^ casr_state[34];
assign o_cmbtr_randbits[169] = lfsr_state[11] ^ casr_state[7];
assign o_cmbtr_randbits[170] = lfsr_state[10] ^ casr_state[5];
assign o_cmbtr_randbits[171] = lfsr_state[34] ^ casr_state[6];
assign o_cmbtr_randbits[172] = lfsr_state[24] ^ casr_state[29];
assign o_cmbtr_randbits[173] = lfsr_state[40] ^ casr_state[2];
assign o_cmbtr_randbits[174] = lfsr_state[5] ^ casr_state[16];
assign o_cmbtr_randbits[175] = lfsr_state[21] ^ casr_state[32];
assign o_cmbtr_randbits[176] = lfsr_state[42] ^ casr_state[13];
assign o_cmbtr_randbits[177] = lfsr_state[38] ^ casr_state[0];
assign o_cmbtr_randbits[178] = lfsr_state[12] ^ casr_state[19];
assign o_cmbtr_randbits[179] = lfsr_state[36] ^ casr_state[16];
assign o_cmbtr_randbits[180] = lfsr_state[22] ^ casr_state[18];
assign o_cmbtr_randbits[181] = lfsr_state[39] ^ casr_state[5];
assign o_cmbtr_randbits[182] = lfsr_state[2] ^ casr_state[25];
assign o_cmbtr_randbits[183] = lfsr_state[34] ^ casr_state[34];
assign o_cmbtr_randbits[184] = lfsr_state[34] ^ casr_state[17];
assign o_cmbtr_randbits[185] = lfsr_state[37] ^ casr_state[36];
assign o_cmbtr_randbits[186] = lfsr_state[35] ^ casr_state[12];
assign o_cmbtr_randbits[187] = lfsr_state[33] ^ casr_state[12];
assign o_cmbtr_randbits[188] = lfsr_state[14] ^ casr_state[30];
assign o_cmbtr_randbits[189] = lfsr_state[36] ^ casr_state[15];
assign o_cmbtr_randbits[190] = lfsr_state[15] ^ casr_state[31];
assign o_cmbtr_randbits[191] = lfsr_state[37] ^ casr_state[14];
assign o_cmbtr_randbits[192] = lfsr_state[11] ^ casr_state[23];
assign o_cmbtr_randbits[193] = lfsr_state[36] ^ casr_state[26];
assign o_cmbtr_randbits[194] = lfsr_state[42] ^ casr_state[14];
assign o_cmbtr_randbits[195] = lfsr_state[24] ^ casr_state[13];
assign o_cmbtr_randbits[196] = lfsr_state[19] ^ casr_state[15];
assign o_cmbtr_randbits[197] = lfsr_state[38] ^ casr_state[13];
assign o_cmbtr_randbits[198] = lfsr_state[0] ^ casr_state[16];
assign o_cmbtr_randbits[199] = lfsr_state[19] ^ casr_state[0];
assign o_cmbtr_randbits[200] = lfsr_state[17] ^ casr_state[16];
assign o_cmbtr_randbits[201] = lfsr_state[15] ^ casr_state[5];
assign o_cmbtr_randbits[202] = lfsr_state[24] ^ casr_state[0];
assign o_cmbtr_randbits[203] = lfsr_state[3] ^ casr_state[14];
assign o_cmbtr_randbits[204] = lfsr_state[27] ^ casr_state[29];
assign o_cmbtr_randbits[205] = lfsr_state[33] ^ casr_state[21];
assign o_cmbtr_randbits[206] = lfsr_state[29] ^ casr_state[18];
assign o_cmbtr_randbits[207] = lfsr_state[38] ^ casr_state[33];
assign o_cmbtr_randbits[208] = lfsr_state[29] ^ casr_state[31];
assign o_cmbtr_randbits[209] = lfsr_state[3] ^ casr_state[20];
assign o_cmbtr_randbits[210] = lfsr_state[30] ^ casr_state[28];
assign o_cmbtr_randbits[211] = lfsr_state[27] ^ casr_state[36];
assign o_cmbtr_randbits[212] = lfsr_state[34] ^ casr_state[12];
assign o_cmbtr_randbits[213] = lfsr_state[16] ^ casr_state[15];
assign o_cmbtr_randbits[214] = lfsr_state[41] ^ casr_state[4];
assign o_cmbtr_randbits[215] = lfsr_state[11] ^ casr_state[18];
assign o_cmbtr_randbits[216] = lfsr_state[42] ^ casr_state[3];
assign o_cmbtr_randbits[217] = lfsr_state[7] ^ casr_state[23];
assign o_cmbtr_randbits[218] = lfsr_state[17] ^ casr_state[14];
assign o_cmbtr_randbits[219] = lfsr_state[13] ^ casr_state[11];
assign o_cmbtr_randbits[220] = lfsr_state[24] ^ casr_state[10];
assign o_cmbtr_randbits[221] = lfsr_state[27] ^ casr_state[23];
assign o_cmbtr_randbits[222] = lfsr_state[9] ^ casr_state[32];
assign o_cmbtr_randbits[223] = lfsr_state[16] ^ casr_state[18];
assign o_cmbtr_randbits[224] = lfsr_state[23] ^ casr_state[16];
assign o_cmbtr_randbits[225] = lfsr_state[2] ^ casr_state[31];
assign o_cmbtr_randbits[226] = lfsr_state[18] ^ casr_state[24];
assign o_cmbtr_randbits[227] = lfsr_state[29] ^ casr_state[21];
assign o_cmbtr_randbits[228] = lfsr_state[9] ^ casr_state[10];
assign o_cmbtr_randbits[229] = lfsr_state[3] ^ casr_state[19];
assign o_cmbtr_randbits[230] = lfsr_state[40] ^ casr_state[6];
assign o_cmbtr_randbits[231] = lfsr_state[5] ^ casr_state[28];
assign o_cmbtr_randbits[232] = lfsr_state[31] ^ casr_state[3];
assign o_cmbtr_randbits[233] = lfsr_state[0] ^ casr_state[23];
assign o_cmbtr_randbits[234] = lfsr_state[1] ^ casr_state[22];
assign o_cmbtr_randbits[235] = lfsr_state[38] ^ casr_state[11];
assign o_cmbtr_randbits[236] = lfsr_state[26] ^ casr_state[22];
assign o_cmbtr_randbits[237] = lfsr_state[16] ^ casr_state[34];
assign o_cmbtr_randbits[238] = lfsr_state[39] ^ casr_state[18];
assign o_cmbtr_randbits[239] = lfsr_state[38] ^ casr_state[30];
assign o_cmbtr_randbits[240] = lfsr_state[34] ^ casr_state[24];
assign o_cmbtr_randbits[241] = lfsr_state[0] ^ casr_state[35];
assign o_cmbtr_randbits[242] = lfsr_state[11] ^ casr_state[6];

endmodule

`endif

